config/routes.rb
Rails.application.routes.draw do

  resources :actions

  resources :specialists

  resources :services

  root 'main#index'

  get '/about', to: 'about#index', as: 'about'

  # get '/services', to: 'services#index', as: 'services'

  # get '/specialists', to: 'specialists#index', as: 'specialists'

  get '/enlist', to: 'enlist#index', as: 'enlist'

  get '/contacts', to: 'contacts#index', as: 'contacts'

  get '/licences', to: 'licences#licences', as: 'licences'

  get '/svidetelstvo', to: 'licences#svidetelstvo', as: 'svidetelstvo'

  get '/roszdravnadzor', to: 'licences#roszdravnadzor', as: 'roszdravnadzor'

  get '/rospotrebnadzor', to: 'licences#rospotrebnadzor', as: 'rospotrebnadzor'

  get '/marketplace', to: 'marketplace#index', as: 'marketplace'

  get '/cost', to: 'cost#index', as: 'cost'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
	has_and_belongs_to_many :specialists
end

app/models/specialist.rb
class Specialist < ApplicationRecord
	has_and_belongs_to_many :services
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/cost_controller.rb
class CostController < ApplicationController
	def index
		
	end
end

app/controllers/enlist_controller.rb
class EnlistController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @specialists = Specialist.all
    @partners = Partner.all
    @actions = Action.all
    @feedback = Feedback.all
    @news = News.all
  end

  def about
  end
  
  def services
  end
  
  def specialists
  end
  
  def enlist
  end
  
  def contacts
  end
  
  def marketplace
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def index
		@face = Service.where('dad = "Косметология лица"')
		@trixology = Service.where('dad = "Трихология"')
		@body = Service.where('dad = "Коррекция фигуры"')
		@analyses = Service.where('dad = "Анализы"')
		@other = Service.where('dad = "Другие услуги"')
	end

	def show
		@service = Service.find(params[:id])		
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cost_helper.rb
module CostHelper
end

app/helpers/enlist_helper.rb
module EnlistHelper
end

app/helpers/licences_helper.rb
module LicencesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/services/index.html.erb
<style type="text/css">
.department-page-details li {
    white-space: nowrap; /* Запрещаем перенос строк */
    overflow: hidden; /* Обрезаем все, что не помещается в область */
    padding: 5px; /* Поля вокруг текста */
    text-overflow: ellipsis;
</style>
            <div class="department-page-area">  
                <div class="container">
		<div class="title-area">
		    <h2 class="title title-bar">Услуги</h2>
		</div>
                    <ul class="department-tab-title">
                        <li class="active">
                            <a href="#face" data-toggle="tab" aria-expanded="false">
                                <i  aria-hidden="true"></i>
                                <p>Косметология лица</p>
                            </a>
                        </li>
                        <li>
                            <a href="#trixology" data-toggle="tab" aria-expanded="false">
                                <i -hidden="true"></i>
                                <p>Трихология</p>
                            </a>
                        </li>
                        <li>
                            <a href="#body" data-toggle="tab" aria-expanded="false">
                                <i -hidden="true"></i>
                                <p>Коррекция фигуры</p>
                            </a>
                        </li>
                        <li>
                            <a href="#analyses" data-toggle="tab" aria-expanded="false">
                                <i  aria-hidden="true"></i>
                                <p>Анализы</p>
                            </a>
                        </li>
                        <li>
                            <a href="#other" data-toggle="tab" aria-expanded="false">
                                <i  aria-hidden="true"></i>
                                <p>Другие услуги</p>
                            </a>
                        </li>
                    </ul>
                </div>  
                <div class="container tab-content">
                    <div class="department-page-details tab-pane fade active in" id="face">
                        <ul>
                        	<% @face.each do |fac| %>
                            <%== "<li><i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>" + link_to(fac.name, service_path(fac.id)) + "</li>" %>
                            <% end %>
                        </ul>
                    </div> 
                    <div class="department-page-details tab-pane fade" id="trixology">
                        <ul>                            
                        	<% @trixology.each do |fac| %>
                            <%== "<li><i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>" + link_to(fac.name, service_path(fac.id)) + "</li>" %>
                            <% end %>
                        </ul>
                    </div>
                    <div class="department-page-details tab-pane fade" id="body">
                        <ul>
                        	<% @body.each do |fac| %>
                            <%== "<li><i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>" + link_to(fac.name, service_path(fac.id)) + "</li>" %>
                            <% end %>
                        </ul>
                    </div>
                    <div class="department-page-details tab-pane fade" id="analyses">
                        <ul>
                        	<% @analyses.each do |fac| %>
                            <%== "<li><i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>" + link_to(fac.name, service_path(fac.id)) + "</li>" %>
                            <% end %>
                        </ul>
                    </div>
                    <div class="department-page-details tab-pane fade" id="other">
                        <ul>
                        	<% @other.each do |fac| %>
                            <%== "<li><i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>" + link_to(fac.name, service_path(fac.id)) + "</li>" %>
                            <% end %>
                        </ul>
                    </div>
                </div>  
            </div> 

app/views/services/show.html.erb
<div class="inner-page-banner-area">
    <div class="container">
        <div class="pagination-area">
            <ul>
                <li><%= @service.dad %></li>
                <li><%= @service.parent %></li>
            </ul>
        </div>
    </div>  
</div>
<div class="department-page-area">  
	<div class="container">
		<div class="title-area">
			<h2 class="title title-bar"><%= @service.name %></h2>
		</div>
	<strong><%= @service.short_desc %></strong>
	<p><%= @service.full_desc %></p>
	</div>

</div>