config/routes.rb
Rails.application.routes.draw do

  resources :actions

  resources :specialists

  resources :services

  root 'main#index'

  get '/about', to: 'about#index', as: 'about'

  # get '/services', to: 'services#index', as: 'services'

  # get '/specialists', to: 'specialists#index', as: 'specialists'

  get '/enlist', to: 'enlist#index', as: 'enlist'

  get '/contacts', to: 'contacts#index', as: 'contacts'

  get '/licences', to: 'licences#licences', as: 'licences'

  get '/svidetelstvo', to: 'licences#svidetelstvo', as: 'svidetelstvo'

  get '/roszdravnadzor', to: 'licences#roszdravnadzor', as: 'roszdravnadzor'

  get '/rospotrebnadzor', to: 'licences#rospotrebnadzor', as: 'rospotrebnadzor'

  get '/marketplace', to: 'marketplace#index', as: 'marketplace'

  get '/cost', to: 'cost#index', as: 'cost'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
	has_and_belongs_to_many :specialists
end

app/models/specialist.rb
class Specialist < ApplicationRecord
	has_and_belongs_to_many :services
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/cost_controller.rb
class CostController < ApplicationController
	def index
		
	end
end

app/controllers/enlist_controller.rb
class EnlistController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @specialists = Specialist.all
    @partners = Partner.all
    @actions = Action.all
    @feedback = Feedback.all
    @news = News.all
  end

  def about
  end
  
  def services
  end
  
  def specialists
  end
  
  def enlist
  end
  
  def contacts
  end
  
  def marketplace
  end
  
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  def index
  	# @glav_vrach = Specialist.find(1)
  	@specialists = Specialist.all
  end

  def show
  	@specialist = Specialist.find(params[:id])	
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cost_helper.rb
module CostHelper
end

app/helpers/enlist_helper.rb
module EnlistHelper
end

app/helpers/licences_helper.rb
module LicencesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/index.html.erb
<style type="text/css">
	div.centre {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
.specialists > div {
	height: 500px;
box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
}


</style>
<div class="brand-area bg-lightPrimary">
	<div class="container">
		<div class="title-area">
		    <h2 class="title title-bar">Наши специалисты</h2>
		</div>
		<div class="row">
			<div class="specialists">
				<% @specialists.each do |specialist| %>
					<%==	"<div class=\"col-xs-4\"><div class=\"team-box1\">" + image_tag("specialists/" + specialist.photo, class: "img-responsive", style: "border-radius: 10px") + "<a href=\"" + specialist_path(specialist) + "\"><div class=\"team-content-wrapper\"><div style=\"clear: both; display: block; width: 80%; padding: 25px 0; background: #3b82ea; position: absolute; top: -70px; border-radius: 5px; text-align: center;  left: 0;    right: 0; margin: 0 auto; color: white\"><h4>" + specialist.name + "</h4><h5>" + specialist.position + "</h5></div></div></div></div>"%>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/specialists/show.html.erb
<div class="brand-area bg-lightPrimary">
	<div class="container">
		<div class="title-area">
		    <h2 class="title title-bar"><%= @specialist.name %></h2>
		</div>
		<div class="row">
			<div class="specialist">
<div class="row col-xs-offset-4">
		<%= image_tag("specialists/" + @specialist.photo, class: "img-responsive", style: "border-radius: 10px") %>
</div>
<div class="row">
		<h4><%= @specialist.position %></h4>
</div>
<div class="row" style="text-align: left">
		<%== @specialist.description %>
</div>
			</div>
		</div>
	</div>
</div>