config/routes.rb
Rails.application.routes.draw do

  resources :actions

  resources :specialists

  resources :services

  root 'main#index'

  get '/about', to: 'about#index', as: 'about'

  # get '/services', to: 'services#index', as: 'services'

  # get '/specialists', to: 'specialists#index', as: 'specialists'

  get '/enlist', to: 'enlist#index', as: 'enlist'

  get '/contacts', to: 'contacts#index', as: 'contacts'

  get '/licences', to: 'licences#licences', as: 'licences'

  get '/svidetelstvo', to: 'licences#svidetelstvo', as: 'svidetelstvo'

  get '/roszdravnadzor', to: 'licences#roszdravnadzor', as: 'roszdravnadzor'

  get '/rospotrebnadzor', to: 'licences#rospotrebnadzor', as: 'rospotrebnadzor'

  get '/marketplace', to: 'marketplace#index', as: 'marketplace'

  get '/cost', to: 'cost#index', as: 'cost'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
	has_and_belongs_to_many :specialists
end

app/models/specialist.rb
class Specialist < ApplicationRecord
	has_and_belongs_to_many :services
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/cost_controller.rb
class CostController < ApplicationController
	def index
		
	end
end

app/controllers/enlist_controller.rb
class EnlistController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @specialists = Specialist.all
    @partners = Partner.all
    @actions = Action.all
    @feedback = Feedback.all
    @news = News.all
  end

  def about
  end
  
  def services
  end
  
  def specialists
  end
  
  def enlist
  end
  
  def contacts
  end
  
  def marketplace
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cost_helper.rb
module CostHelper
end

app/helpers/enlist_helper.rb
module EnlistHelper
end

app/helpers/licences_helper.rb
module LicencesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/about/index.html.erb
<div class="brand-area bg-lightPrimary">
	<div class="container">
	<div class="row">
		<%= image_tag "about/team.jpg", class: "img-responsive" %>
</div>
<br/>
	<div class="row">
	<h4 style="text-align: justify; ">
Красоту, как и драгоценность, нужно держать в надлежащем виде и мы как истинные ювелиры, профессионалы своего дела, стоим на страже красоты.
Центр Эстетической Медицины – это уверенность в получении результата, а в сфере красоты, это тончайшее ювелирное мастерство, блюстители которого высококлассная команда профессионалов, в их распоряжении поставлена лучшая техника и образцы новейших препаратов в сфере косметологии.
Центр Эстетической Медицины – это уровень и качество обслуживания. Мы знаем, что нужно для достижения высот в нашем деле – это природный талант, тонкое понимание красоты, качественное образование и большой опыт. В нашем центре подобрана лучшая команда специалистов, врачей, которые знают, любят свое дело. Ведь профессионалы любящие свою работу, всегда достигают желаемых результатов.
Центр Эстетической медицины работает в трех направлениях:
Эстетическая косметология, а именно косметологические программы по лечению, омоложению, восстановлению и устранению эстетических недостатков кожи.

Инъекционная косметология - различные инъекционные методики, применяемые специалистами в борьбе с возрастными изменениями кожи, акне, и другими несовершенствами.

Аппаратная косметология, уникальные методики коррекции кожи лица и фигуры.
В нашем центре неизменно подкрепляется гармонизацией состояние здоровья пациента, перенаправление на качественный и более высокий уровень жизни.
</h4>

<table>
	<tr>
		<td>
		<%= link_to image_tag("about/icons/orel.jpg", border: 0), licences_path %>
</td>
<td>
Лицензии Департамента здравоохранения города Москвы</td>
		<td>
		<%= link_to image_tag("about/icons/fns.png", border: 0), svidetelstvo_path %>
</td>
		<td>
		Свидетельство о государственной регистрации в качестве юридического лица</td>
		<td>
		<%= link_to image_tag("about/icons/roszdravnadzor.png", border: 0), roszdravnadzor_path %>
</td>
		<td>Территориальный орган Росздравнадзора по г. Москве и Московской области</td>
		<td>
		<%= link_to image_tag("about/icons/upravlenie-fed-slyzhbi.png", border: 0), rospotrebnadzor_path %>
</td>
		<td>Управление Федеральной службы по надзору в сфере защиты прав потребителей и благополучия человека по городу Москве</td>
	</tr>
</table>
	</div>
</div>
</div>	

app/views/enlist/index.html.erb
<div class="brand-area bg-lightPrimary">
<div class="container">
                    <div class="row contact-wrapper">                       
                        <div class="col-lg-8 col-md-6 col-sm-12 col-xs-12">
                            <div class="contact-form-area">
                                <h2 class="title-table">Оставить заявку</h2>
                                <form id="contact-form"> 
                                    <fieldset>     
                                        <div class="row contact-form-inner">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group">
                                                    <input type="text" placeholder="Имя" class="form-control" name="name" id="form-name" data-error="Name field is required" required>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                               <div class="form-group">
                                                    <input type="date" placeholder="Дата" class="form-control" name="email" id="form-email" data-error="Email field is required" required>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group">
                                                    <input type="text" placeholder="Услуга" class="form-control" name="subject" id="form-subject" data-error="Subject field is required" required>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="form-group">
                                                    <textarea placeholder="Контактные данные" class="textarea form-control" name="message" id="form-message" rows="2" cols="20" data-error="Message field is required" required></textarea>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>
                                            <button type="submit" class="book-now-btn"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                            <div class='form-response'></div>
                                        </div>
                                    </fieldset>
                                </form> 
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                            <div class="contact-info-area">
                                <h2 class="title-table">Контактная информация</h2>
                                <div class="contact-info-inner">
                                    <ul>
                                        <li><i class="fa fa-phone" aria-hidden="true"></i>8 (800) 333-20-25</li>
                                        <li><i class="fa fa-print" aria-hidden="true"></i>ежедневно: с 10:00 до 20:00</li>
                                        <li><i class="fa fa-map-marker" aria-hidden="true"></i>г. Москва, Маросейка ул., 10/1, стр.2</li>
                                    </ul>
                                    <!-- <p>Don`t hesitate to talk</p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>