config/routes.rb
Rails.application.routes.draw do

  resources :actions

  resources :specialists

  resources :services

  root 'main#index'

  get '/about', to: 'about#index', as: 'about'

  # get '/services', to: 'services#index', as: 'services'

  # get '/specialists', to: 'specialists#index', as: 'specialists'

  get '/enlist', to: 'enlist#index', as: 'enlist'

  get '/contacts', to: 'contacts#index', as: 'contacts'

  get '/licences', to: 'licences#licences', as: 'licences'

  get '/svidetelstvo', to: 'licences#svidetelstvo', as: 'svidetelstvo'

  get '/roszdravnadzor', to: 'licences#roszdravnadzor', as: 'roszdravnadzor'

  get '/rospotrebnadzor', to: 'licences#rospotrebnadzor', as: 'rospotrebnadzor'

  get '/marketplace', to: 'marketplace#index', as: 'marketplace'

  get '/cost', to: 'cost#index', as: 'cost'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
	has_and_belongs_to_many :specialists
end

app/models/specialist.rb
class Specialist < ApplicationRecord
	has_and_belongs_to_many :services
end

app/controllers/cost_controller.rb
class CostController < ApplicationController
	def index
		
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @specialists = Specialist.all
    @partners = Partner.all
    @actions = Action.all
    @feedback = Feedback.all
    @news = News.all
  end

  def about
  end
  
  def services
  end
  
  def specialists
  end
  
  def enlist
  end
  
  def contacts
  end
  
  def marketplace
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cost_helper.rb
module CostHelper
end

app/helpers/enlist_helper.rb
module EnlistHelper
end

app/helpers/licences_helper.rb
module LicencesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Центр эстетической медицины</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="wrapper">
	        <!-- Header Area Start Here -->
	        <header>                
	            <div class="header2-area">
	                <div class="header-top-area">
	                    <div class="container">
	                        <div class="row">
	                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
	                                <div class="header-top-left">
	                                    <ul>
	                                        <li><i class="fa fa-phone" aria-hidden="true"></i><a href="Tel:88003332025"> 8 (800) 333-20-25
	                                        многоканальный с 10-00 до 20-00 </a></li>
	                                        <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">info@centerestetmedicina.ru</a></li>
	                                    </ul>
	                                </div>
	                            </div>
	                            <!-- <div class="col-lg-6 col-md-6 col-sm-4 col-xs-12">
	                                <div class="header-top-right">
	                                    <ul>
	                                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
	                                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
	                                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
	                                        <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
	                                    </ul>
	                                </div>
	                            </div> -->
	                        </div>
	                    </div>
	                </div>
	                <div class="header-bottom-area" id="sticker">
	                    <div class="container">
	                        <div class="row">                         
	                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
	                                <div class="logo-area">
	                                    <a href="<%= root_path %>"><%= image_tag "logo.png", class: "img-responsive",  alt: "logo", style: '-webkit-filter: drop-shadow(5px 5px 5px #222); filter: drop-shadow(5px 5px 5px #222);' %></a>
	                                </div>
	                            </div>  
	                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
	                                <div class="main-menu-area">
	                                    <nav>
	                                        <ul>
	                                            <li><%= link_to "ГЛАВНАЯ", root_path %></li>
	                                            <li><%= link_to "О КЛИНИКЕ", about_path %></li>
	                                            <li><%= link_to "УСЛУГИ", services_path %></li>
	                                            <li><%= link_to "СПЕЦИАЛИСТЫ", specialists_path %></li>
	                                            <li><%= link_to "ЗАПИСЬ НА ПРИЁМ", enlist_path %></li>
	                                            <li><%= link_to "КОНТАКТЫ", contacts_path %></li>
	                                            <li><%= link_to "МАРКЕТПЛЕЙС", marketplace_path %></li>
	                                        </ul>
	                                    </nav>
	                                </div>
	                            </div>   
	                            <!-- <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
	                                <ul class="header-cart-area">
	                                    <li class="header-search">
	                                        <form>
	                                            <input type="text" class="search-form" placeholder="Search...." required="">                                    
	                                            <a href="#" class="search-button" id="search-button"><i class="fa fa-search" aria-hidden="true"></i></a>
	                                        </form>
	                                    </li>
	                                </ul>
	                            </div>  -->
	                        </div>                          
	                    </div> 
	                </div>
	            </div>
	            <!-- Mobile Menu Area Start -->
	            <div class="mobile-menu-area">
	                <div class="container">
	                    <div class="row">
	                        <div class="col-md-12">
	                            <div class="mobile-menu">
	                                <nav id="dropdown">
	                                    <ul>
	                                        <li><%= link_to "ГЛАВНАЯ", root_path %>
	                                        </li>
	                                        <li><%= link_to "О КЛИНИКЕ", about_path %>
	                                        </li>
	                                        <li><%= link_to "УСЛУГИ", services_path %></li>
	                                        <li><%= link_to "СПЕЦИАЛИСТЫ", specialists_path %>
	                                        </li>
	                                        <li><%= link_to "ЗАПИСЬ НА ПРИЁМ", enlist_path %>
	                                        </li>
	                                        <li><%= link_to "КОНТАКТЫ", contacts_path %>
	                                        </li>
	                                        <li><%= link_to "МАРКЕТПЛЕЙС", marketplace_path %></li>
	                                    </ul>                                        
	                                </nav>
	                            </div>           
	                        </div>
	                    </div>
	                </div>
	            </div>  
	                <!-- Mobile Menu Area End -->
	        </header>
    <%= yield %>
		  <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Abef757a426a59a6c926a221eb3b117d9c398867feb04d718f022fbffda5a89d6&amp;width=100%25&amp;height=720&amp;lang=ru_RU&amp;scroll=true"></script>
    	<footer>
	        <div class="footer-area-top section-space">
	            <div class="container">
	                <div class="row">
	                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
	                        <div class="footer-box">
	                            <%= image_tag "foot_logo.png", class: "img-responsive",  alt: "logo" %>
	                        </div>
	                    </div>
	                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
	                    <h4>г. Москва, Маросейка ул., 10/1, стр.2</h4>
	                    </div>
	                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		                    <a href="Tel:88003332025"><h2>8 (800) 333-20-25</h2></a>
							<h4>многоканальный с 10-00 до 20-00</h4>
						</div>
	                </div>
	            </div>
	        </div>
	        <div class="footer-area-bottom">
	            <div class="container">
	                <h2><%= link_to "ЦЕНЫ", cost_path %></h2>
	            </div>
	        </div>
	    </footer>
	<a id="scrollUp" href="#top" style="display: none; position: fixed; z-index: 2147483647;"><i class="fa fa-arrow-up"></i></a>
  </body>
</html>